// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_customer_birthday_col_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_customer_birthday_col_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201808160134443_fix_customer_birthday_col_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
