// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_customer_birthday_values : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_customer_birthday_values));
        
        string IMigrationMetadata.Id
        {
            get { return "201808160113199_add_customer_birthday_values"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
